apiVersion: v1
kind: Service
metadata:
  name: {{ include "budgetscanner.fullname" . }}
  labels:
    {{- include "budgetscanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "budgetscanner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
