apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "budgetscanner.fullname" . }}-config
  labels:
    {{- include "budgetscanner.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.app.env.port | quote }}
  NODE_ENV: {{ .Values.app.env.nodeEnv | quote }}
  CLIENT_URL: {{ include "budgetscanner.clientUrl" . | quote }}
