{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled (not .Values.mongodb.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "budgetscanner.mongodb.fullname" . }}-data
  labels:
    {{- include "budgetscanner.mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  {{- if .Values.mongodb.persistence.storageClass }}
  {{- if (eq "-" .Values.mongodb.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
