apiVersion: v1
kind: Secret
metadata:
  name: {{ include "budgetscanner.fullname" . }}-secret
  labels:
    {{- include "budgetscanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ include "budgetscanner.mongodb.uri" . | quote }}
{{- if .Values.mongodb.auth.enabled }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}
{{- end }}
